spring.application.name=ms-product-db
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/eccomers?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=020286
#Agregala clave de la base de datos en spring.datasource.password, 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect